# Лабораторная работа №1
## Выполнил студент группы БВТ2105 Соколов Юрий Александрович

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [1]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [2]:
import random
import time
import numpy as np

In [3]:
# Вводим параметры
user_m = int(input())
user_n = int(input())
user_min_limit = int(input())
user_max_limit = int(input())
# Генерируем матрицу в зависимости от параметров
def Matrix(user_m, user_n, user_min_limit, user_max_limit):
    # Создаем одномерный массив, который будет содержать другой массив - строки матрицы
    matrix2d = []
    # В каждую ячейку добавляем по массиву
    for i in range(user_m):
        matrix1d = []
        # Заполняем строки матрицы случайнвми числами
        for j in range(user_n):
            matrix1d.append(random.randint(user_min_limit, user_max_limit))
        matrix2d.append(matrix1d)
    return matrix2d
print(np.array(Matrix(user_m, user_n, user_min_limit, user_max_limit)))

1
1
1
10
[[10]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [14]:
import copy
import math

In [16]:
# Сортировка обменом. || Сортировка пузырьком.
start_time = time.time()
# Сгенерируем матрицу
unsortArr = Matrix(10,10,0,1000)
print("неотсортированная матрица: ")
print(np.array(unsortArr))
# Напишем функцию сортировки для одномерного массива
def booble_sort(array):
    # Создадим переменную для длины массива, которую будем изменять
    length = len(array)
    while(length != 0):
        # Запустим цикл, который за свою итерацию поставит максимальный элемент
        # на свое последнее место
        for i in range(1, length):
            if array[i] < array[i-1]:
                temp = array[i-1]
                array[i-1] = array[i]
                array[i] = temp
        length -= 1
    return array   
# Напишем функцию сортировки матрицы
def matrix_sort(array2d):
    for i in range(0, len(array2d)):
        booble_sort(array2d[i])
    return array2d
# Выведем отсортированную матрицу    
print("отсортированная матрица: ")
print(np.array(matrix_sort(unsortArr)))
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

неотсортированная матрица: 
[[549 881 692 697 542 221 663 455 911 712]
 [505 996 354 932 487 715 544 820  51 135]
 [999 296 934 417 559 558 245 421 504 389]
 [503 742 294 663 476 598 475 460 992 457]
 [149 211  27  59 248  64 697  88 380 216]
 [ 45 624 188 421 389 287 943 416 815 741]
 [226 893 585   0 878 323 336 723 532 474]
 [693  21 426 570 613 251 452 964 415 113]
 [693 993 611 582 454 897 189 793 920 358]
 [913 274 629 865  91 351 702 854 580 257]]
отсортированная матрица: 
[[221 455 542 549 663 692 697 712 881 911]
 [ 51 135 354 487 505 544 715 820 932 996]
 [245 296 389 417 421 504 558 559 934 999]
 [294 457 460 475 476 503 598 663 742 992]
 [ 27  59  64  88 149 211 216 248 380 697]
 [ 45 188 287 389 416 421 624 741 815 943]
 [  0 226 323 336 474 532 585 723 878 893]
 [ 21 113 251 415 426 452 570 613 693 964]
 [189 358 454 582 611 693 793 897 920 993]
 [ 91 257 274 351 580 629 702 854 865 913]]
--- 1 ms ---


In [5]:
# Сортировка выбором.
start_time = time.time()
# Сгенерируем матрицу для которой проведем сортировку
unsortArr = Matrix(10,10,0,1000)
print("неотсортированная матрица: ")
print(np.array(unsortArr))
# Напишем функцию сортировки для одномерного массива
def selection_sort(array):
    # Будем проходить по элементам массива, запоминая минимальным индекс первого элемента
    # в неотсортированной части массива. В результате полного перебора последний элемент
    # будет на своем месте поэтому его не включаем
    for i in range(0, len(array)-1):
        min_index = i
        # внутрениим циклом проходя по неотсортированной части массива, определим индекс
        # минимального элемента
        for j in range(i+1, len(array)):
            if array[j] < array[min_index]:
                min_index = j
        # Если первый неотсортированный элемент так и остался минимальным, то он стоит
        # на своем месте и нужно лишь сдвинуть цикл. Если нашелся другой минимальный элемент
        # то поменяем элементы местами
        if (min_index != i):
            temp = array[min_index]
            array[min_index] = array[i]
            array[i] = temp
    return array
# Напишем функцию сортировки матрицы
def matrix_sort(array2d):
    for i in range(0, len(array2d)):
        selection_sort(array2d[i])
    return array2d
# Выведем отсортированную матрицу    
print("отсортированная матрица: ")
print(np.array(matrix_sort(unsortArr)))
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

неотсортированная матрица: 
[[755 461 224 784 202 213 598 883 359 533]
 [967 332 737   9  16  62 413 331  49  83]
 [378 282 785 511 989 280 155 247 533 314]
 [127 179 887   5  74 696 513 416 282 348]
 [440 211 884 702 215 927 777 326 515 804]
 [702 889 491 168 919 235 199 502 925 413]
 [ 89 488  89 182 232 451 144 424 635 958]
 [146 737 901 129 219 407 640 757 561 801]
 [842 610 786 573 271 210 912 876 376 203]
 [461 165 846 187 697 908 421 935 818 138]]
отсортированная матрица: 
[[202 213 224 359 461 533 598 755 784 883]
 [  9  16  49  62  83 331 332 413 737 967]
 [155 247 280 282 314 378 511 533 785 989]
 [  5  74 127 179 282 348 416 513 696 887]
 [211 215 326 440 515 702 777 804 884 927]
 [168 199 235 413 491 502 702 889 919 925]
 [ 89  89 144 182 232 424 451 488 635 958]
 [129 146 219 407 561 640 737 757 801 901]
 [203 210 271 376 573 610 786 842 876 912]
 [138 165 187 421 461 697 818 846 908 935]]
--- 1 ms ---


In [6]:
# Сортировка вставкой.
start_time = time.time()
# Сгенерируем матрицу
unsortArr = Matrix(10,10,0,1000)
print("неотсортированная матрица: ")
print(np.array(unsortArr))
# Напишем функцию сортировки для одномерного массива
def insertion_sort(array):
    # Предположим, что первый элемент массива отсортирован, пройдемся в цикле по
    # остальной неотсортированной части массива
    for i in range(1, len(array)):
        # создадим переменную, показывающую на каком элементе кончается
        # отсортированная часть массива
        sorted_arr = i-1
        # Если максимальный элемент отсортированной части больше следуещего
        # и в отсортированной части элементы не отсортированы вставляем элемент
        # в отсортированную часть на свое место
        while array[sorted_arr] > array[sorted_arr+1] and sorted_arr > -1:
            # меняем последний отсортированный местами со следующим неотсортированным
            temp = array[sorted_arr]
            array[sorted_arr] = array[sorted_arr+1]
            array[sorted_arr+1] = temp
            # внутри отсортированной части проверяем, стоит ли на своем месте введенный элемент
            sorted_arr -= 1
    return array    
# Напишем функцию сортировки матрицы
def matrix_sort(array2d):
    for i in range(0, len(array2d)):
        insertion_sort(array2d[i])
    return array2d
# Выведем отсортированную матрицу    
print("отсортированная матрица: ")
print(np.array(matrix_sort(unsortArr)))
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

неотсортированная матрица: 
[[840 303 504 245  63 213 670 120 746 408]
 [671 373 559 680 318 497 913 722 456 241]
 [254 776 586 947 410 546 485 275  57 356]
 [ 98 864 260 207 405 422 165 245 826 307]
 [747 529 817 666 128  83 613 748 834 783]
 [687 117 812 869 223 202 589  32 160 659]
 [261 733 459 343 446 885 730 832   9 210]
 [  1 429 855  51 649 378 545 502 932 282]
 [938 625 858 365 584 231 894 424 997 870]
 [132  99 630 561 666 338 613 150 809 272]]
отсортированная матрица: 
[[ 63 120 213 245 303 408 504 670 746 840]
 [241 318 373 456 497 559 671 680 722 913]
 [ 57 254 275 356 410 485 546 586 776 947]
 [ 98 165 207 245 260 307 405 422 826 864]
 [ 83 128 529 613 666 747 748 783 817 834]
 [ 32 117 160 202 223 589 659 687 812 869]
 [  9 210 261 343 446 459 730 733 832 885]
 [  1  51 282 378 429 502 545 649 855 932]
 [231 365 424 584 625 858 870 894 938 997]
 [ 99 132 150 272 338 561 613 630 666 809]]
--- 2 ms ---


In [17]:
# Сортировка Шелла.
start_time = time.time()
# Сгенерируем матрицу
unsortArr = Matrix(10,10,0,1000)
print("неотсортированная матрица: ")
print(np.array(unsortArr))
# Напишем функцию сортировки для одномерного массива
def shell_sort(array):
    # Выберем первоначальное расстояние между элементами для сортировки
    step = len(array)//2
    # Запустим цикл для сортировки с изменением шага
    while step > 0:
        # Внутри шагового цикла запустим стандартную сортировку вставками
        for i in range(step, len(array)):
            sorted_arr = i
            while array[sorted_arr - step] > array[sorted_arr] and sorted_arr >= step:
                temp = array[sorted_arr - step]
                array[sorted_arr - step] = array[sorted_arr]
                array[sorted_arr] = temp
                sorted_arr -= step
        # уменьшим шаг
        step //= 2
    return array    
# Напишем функцию сортировки матрицы
def matrix_sort(array2d):
    for i in range(0, len(array2d)):
        shell_sort(array2d[i])
    return array2d
# Выведем отсортированную матрицу    
print("отсортированная матрица: ")
print(np.array(matrix_sort(unsortArr)))
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

неотсортированная матрица: 
[[  1   2 208  95 257 915 896 906 216 683]
 [ 26 844 584 639  12 434 507 682 902 744]
 [647  54 978 671 373 186 578  51 129  73]
 [ 51 797 854 907 305   2 233 691 516 604]
 [268 634  53 398 259 650 275 780  13 902]
 [202 653  68 355 851  41 618 504 406  63]
 [515 438 701 749 312 665  34 145 546 611]
 [999 188 370 516 477 385 573 637 411 664]
 [633 778 429  47 150 159 545  25  57 242]
 [784 967 340 404 597 534 457 499 974 404]]
отсортированная матрица: 
[[  1   2  95 208 216 257 683 896 906 915]
 [ 12  26 434 507 584 639 682 744 844 902]
 [ 51  54  73 129 186 373 578 647 671 978]
 [  2  51 233 305 516 604 691 797 854 907]
 [ 13  53 259 268 275 398 634 650 780 902]
 [ 41  63  68 202 355 406 504 618 653 851]
 [ 34 145 312 438 515 546 611 665 701 749]
 [188 370 385 411 477 516 573 637 664 999]
 [ 25  47  57 150 159 242 429 545 633 778]
 [340 404 404 457 499 534 597 784 967 974]]
--- 1 ms ---


In [19]:
# Быстрая сортировка.
start_time = time.time()
# Сгенерируем матрицу
unsortArr = Matrix(10,10,0,1000)
print("неотсортированная матрица: ")
print(np.array(unsortArr))
# Сортировка Хоара состоит из нескольких функций, напишем их
# Функция partition является ядром сортировки, она принимает массив и два указателя
# и постепенно сдвигая указатели создает два отсортированных относительно друг друга
# подмассива относительно опорного, все элементы слева от опорного меньше любого правого
def partition(array, left, right):
    # Создадим переменную разделитель, отвечающую за опорный элемент, выберем последний элемент
    pivot = array[right]
    # Для удобства переобозначим элементы и раз последий элемент опорный, сдвинем правый указатель
    i = left
    j = right - 1
    # пока указатели не встретятся запустим цикл
    while i < j:
        # будем сдвигать указатели к опорному, если они на своих местах и их не нужно переставлять
        while array[i] < pivot and i < right:
            i +=1
        while (array[j] >= pivot and j > left):
            j -=1
        # дойдя до элементов которые не соответсвуют своим областям
        # где элемент слева больше опорного, а справа меньше. Если при этом
        # указатели не встретились, поменяем их местами и сдвинем указатели
        if i < j:
            array[i], array[j] = array[j], array[i]
            i +=1
            j -=1
    # После отсортировывания элементов относительно опорного,
    # поставим опорный на нужное место
    if array[i] > pivot:
        array[i], array[right] = array[right], array[i]
    # вернем индекс элемента относительно которого элементы слева меньше любого элемента справа
    return i
# Напишем функцию самой сортировки, которая будет представлена двумя рекрусиями
def quick_sort(array, start, end):
    if start < end:
        right_start = partition(array, start, end)
        quick_sort(array, start, right_start - 1)
        quick_sort(array, right_start + 1 , end)
# Напишем функцию сортировки матрицы
def matrix_sort(array2d):
    for i in range(0, len(array2d)):
        quick_sort(array2d[i], 0, len(array2d[i])-1)
    return array2d
# Выведем отсортированную матрицу    
print("отсортированная матрица: ")
print(np.array(matrix_sort(unsortArr)))
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

неотсортированная матрица: 
[[773 439 352  52 579  28 261 989 743 950]
 [797 522 610  33 838 332 866 535 501 190]
 [694 568 992 486 176  90 265 518 854 687]
 [232 300 784 148 391 593 897 979 339  21]
 [172 786 380 261 759 580 407  15 899 772]
 [577 686 715 188 610 650 328 850 775 939]
 [273 513 589 455 896 596 677  12 493 860]
 [965 434 580 994 510 637 808 951 262 299]
 [957  89 311 889 243 798 343 112 221 505]
 [751 182 436 839  49 874 140 846 982 273]]
отсортированная матрица: 
[[ 28  52 261 352 439 579 743 773 950 989]
 [ 33 190 332 501 522 610 797 535 838 866]
 [ 90 176 265 486 518 568 687 694 854 992]
 [ 21 148 232 300 339 391 593 784 897 979]
 [ 15 172 261 380 407 580 759 772 786 899]
 [188 328 577 610 650 686 715 775 850 939]
 [ 12 273 493 455 513 589 596 677 860 896]
 [262 299 434 510 580 637 808 951 965 994]
 [ 89 112 221 243 311 343 505 798 889 957]
 [ 49 140 182 273 436 751 839 846 874 982]]
--- 2 ms ---


In [21]:
import heapq
# Турнирная сортировка.
start_time = time.time()
# Для турнирной сортировки необходимо использовать маленькую трех-уровневую кучу из 7 элементов
# эта куча будет принимать в себя массив и распологать данные из него в минимально древовидном порядке
# где на самом нижнем уровне самый минимальный элемент и каждый родитель меньше потомка

# Вспомогательная функция для объединения отсортированных массивов
def merge_arrays(arrayOfArrays):
    # Если массив один, преобразуем его из двумерного в одномерный
    if len(arrayOfArrays) == 1:
        return arrayOfArrays[0]
    # Если массивов несколько, создадим результирующий и отсортируем массивы по убыванию
    result = []
    arrayOfArrays.sort(reverse=True)
    # Будем в цикле перебирать два одномерных массива, формируя один отсортированный, который
    # затем пойдет на следующую итерацию цикла для объединения со следующим и т.д.
    for i in range(0, len(arrayOfArrays)-1):
        while arrayOfArrays[i] and arrayOfArrays[i+1]:
            # Пока массивы не пусты, будем вынимать первый элемент в соответствии с условием
            if arrayOfArrays[i][0] < arrayOfArrays[i+1][0]:
                result.append(arrayOfArrays[i].pop(0))
            else:
                result.append(arrayOfArrays[i+1].pop(0))
        # Если по итогу опустел i-ый массив, то по выходу из цикла остался не записанный в результат
        # i+1 массив, добавим его к результату, иначе добавим i-ый
        if not arrayOfArrays[i]:
            result += arrayOfArrays[i+1]
        else:
            result += arrayOfArrays[i]
        arrayOfArrays[i+1] = result
    return result

def tournament_sort(arr):
    # Создадим массив, который будет содержать отсортированные массивы победителей
    all_winners = []
    flag = True
    while flag:
        # Создадим массив данных, состоящий из 7 элементов, куда занесем первые 7 элементов массива
        data = []
        if len(arr) >= 7:
            for i in range(0, 7):
                data.append(arr[i])
            i = 7
        # Если исходный массив содержит меньше чем 7 элементов, то просто выгрузим что есть в данные
        else:
            data = arr
            i = len(data)+1
        # Прервратим данные в кучу, которая по умолчанию выведет минимальный элемент на нижний уровень
        heapq.heapify(data)
        # Создадим массив проигравших и массив победителей
        losers = []
        winners = []
        # Занесем первый минимальный элемент из кучи в массив победителей, при этам после изъятия
        # элемента из кучи, куча переформируется сохранив древовидную структуру
        winners.append(heapq.heappop(data))
        # Будем пополнять кучу пока не закончится сортируемый массив
        while i < len(arr):
            # Сравним последний элемент массива победителей с элементом который собираемся внести в кучу
            # Если он больше, то добавим его в кучу, если равен, то внесем в победители, иначе в проигравшие
            if arr[i] > winners[-1]:
                heapq.heappush(data, arr[i])
                # Если мы внесли элемент в кучу, то сразу достанем из нее нижний элемент и внесем в победители
                winners.append(heapq.heappop(data))
            elif arr[i] == winners[-1]:
                winners.append(arr[i])
            else:
                losers.append(arr[i])
            i +=1
        # По итогам итерации, мы перенесли все элементы в массивы победителей и проигравших
        # Занесем оставшиеся в куче элементы в победителей
        while data:
            winners.append(heapq.heappop(data))
        
        flag = False
        # Добавим партию победителей в массив всех победителей
        all_winners.append(winners)
        # Если у нас есть проигравшие, то для них запустим еще одну итерацию сортировки
        if losers:
            arr = losers
            flag = True
    # Получив отосртированные массивы победителей, объединим их сохранив сортировку
    return merge_arrays(all_winners)
       
        
# Функция сортировки матрицы
def matrix_sort(array2d):
    array2d2 = []
    for i in range(0, len(array2d)):
        array2d2.append(tournament_sort(array2d[i]))
    return array2d2
# Сгенерируем матрицу
unsortArr = Matrix(10,10,0,1000)
print("неотсортированная матрица: ")
print(np.array(unsortArr))
# Выведем отсортированную матрицу    
print("отсортированная матрица: ")
print(np.array(matrix_sort(unsortArr)))
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

неотсортированная матрица: 
[[ 431  368  457  209  914  290  725  476  486  468]
 [ 357  913  432  207  781   91  880   99  369  550]
 [ 719  970  768   54  453  989  910  449  436   45]
 [ 371  244  870  914  913  826   37  828  280  662]
 [ 968  823  631  764  455  705  994  550  151  851]
 [  57  426  690  756   45  110  918  468  428  318]
 [  15   68  545  344  206  771  746  586  945  930]
 [ 290  813  961  643  236 1000  308  432  910  989]
 [ 665  627  209  237  329   42  477  974  672  163]
 [ 862  910  964  489  153  914  331  966  447  712]]
отсортированная матрица: 
[[ 209  290  368  431  457  468  476  486  725  914]
 [  91   99  207  357  369  432  550  781  880  913]
 [  45   54  436  449  453  719  768  910  970  989]
 [  37  244  280  371  662  826  828  870  913  914]
 [ 151  455  550  631  705  764  823  851  968  994]
 [  45   57  110  318  426  428  468  690  756  918]
 [  15   68  206  344  545  586  746  771  930  945]
 [ 236  290  308  432  643  813  910  961  9

### Вывод


В результате проделанной работы, мы научились писать некоторые популярные сортировки в python, поняли как анализировать эффективность алгоритмов по времени и по памяти, сравнили сортировки по уровню эффективности и построили графики.